### ISSUE TITLE
Application is crashing when accessing Communication Hub with no Asterisk connection

### ISSUE THREAD

**Issue by Shern** [Bathlamos/RTDC#109]
When clicking on Communication Hub in the navigation drawer, the interface is drawn but the application also crashes.

**Comment by Shern** [comment]
10-18 20:40:00.362    2042-2042/rtdc.android E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: rtdc.android, PID: 2042
    java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
            at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
            at java.util.ArrayList.get(ArrayList.java:308)
            at rtdc.core.controller.CommunicationHubController.sortRecentContacts(CommunicationHubController.java:45)
            at rtdc.core.controller.CommunicationHubController.onRecentContactsFetched(CommunicationHubController.java:72)
            at rtdc.core.event.FetchRecentContactsEvent.fire(FetchRecentContactsEvent.java:41)
            at rtdc.core.event.Event.fire(Event.java:46)
            at rtdc.core.service.Service$1.onSuccess(Service.java:117)
            at rtdc.core.service.Service$1.onSuccess(Service.java:109)
            at rtdc.android.impl.AndroidHttpRequest$1.onResponse(AndroidHttpRequest.java:62)
            at rtdc.android.impl.AndroidHttpRequest$1.onResponse(AndroidHttpRequest.java:58)
            at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:67)
            at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:30)
            at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:5942)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

**Comment by Shern** [comment]
Solved in commit https://github.com/Bathlamos/RTDC/commit/11402b40611060d0e5893498c020a5f2796d7f55
