### ISSUE TITLE
Bugs and problems in date of March 27

### ISSUE THREAD

**Issue by Shern** [Bathlamos/RTDC#48]
- **FIXED** Delete user not implemented. 
- **FIXED** Delete unit not implemented. 
- **FIXED** Edit description of action not working
- **FIXED** Rename Cancel button when editing user or account to delete ? Confusing
- **FIXED** Show time only in action plan deadline instead of full date?
- **FIXED** Sorting in Capcity Overview does not seem to work except for Unit Name column
- No sorting in Action Plan?
- **FIXED** Update of Role, Target and Deadline in Action does not seem to work. It's like when editing, a new Action is inserted in the database.
- **FIXED** Application crashed when trying to modify deadline:
	 java.lang.IllegalStateException: Could not find a method onDeadlineClick(View) in the activity class rtdc.android.presenter.CreateActionActivity for onClick handler on view class rtdc.android.impl.AndroidUiDate with id 'deadlineEdit'
            at android.view.View$1.onClick(View.java:3956)
            at android.view.View.performClick(View.java:4633)

**Comment by Shern** [comment]
- Crash when adding a new user:
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@42daa138 is not valid; is your activity running?
            at android.view.ViewRootImpl.setView(ViewRootImpl.java:750)
            at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:278)
            at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
            at android.app.Dialog.show(Dialog.java:288)
            at android.app.AlertDialog$Builder.show(AlertDialog.java:951)
            at rtdc.android.presenter.CreateUserActivity.displayError(CreateUserActivity.java:259)
            at rtdc.core.controller.Controller.onError(Controller.java:18)
            at rtdc.core.event.ErrorEvent.fire(ErrorEvent.java:34)
            at rtdc.core.event.Event.fire(Event.java:33)
            at rtdc.core.service.Service$1.onSuccess(Service.java:99)
            at rtdc.core.service.Service$1.onSuccess(Service.java:91)
            at rtdc.android.impl.AndroidHttpRequest$1.onResponse(AndroidHttpRequest.java:63)
            at rtdc.android.impl.AndroidHttpRequest$1.onResponse(AndroidHttpRequest.java:59)

**Comment by Shern** [comment]
- Can't delete User because of foreign key in table usercredentials

**Comment by Shern** [comment]
- Phone number is not saved in DB

**Comment by Shern** [comment]
- When updating a unit, crash because it trys to add the same unit.

**Comment by Nicolas-M** [comment]
* When signing in with an invalid username and/or password, the application crashes:
 `java.lang.NullPointerException
            at rtdc.android.presenter.fragments.UserFragment.displayError(UserFragment.java:82)
            at rtdc.core.controller.Controller.onError(Controller.java:18)
            at rtdc.core.event.ErrorEvent.fire(ErrorEvent.java:34)
            at rtdc.core.event.Event.fire(Event.java:33)`

**Comment by Shern** [comment]
- Wishlist: When finishing editing/adding an Unit, it would be nice if the Unit tab of the Admin view is active instead of User.

**Comment by Shern** [comment]
No bug remaining in the list, woot!

**Comment by Shern** [comment]
- Status in action plan is not updated.

**Comment by Nicolas-M** [comment]
Separate issues have been created for the remaining bugs:
* #57 Sorting the Action Plan
* #60 Move the password to it's own dialog

As for the status not being updated, I'll take a look when I add the edit functionality back as part of my redesign (#56).
