### ISSUE TITLE
Communication Hub & Manage Users Crash

### ISSUE THREAD

**Issue by Nicolas-M** [Bathlamos/RTDC#68]
The application crashes when you go to the communication hub, and then the manage users (using the drawer menu). Here is the stack trace:
```
java.lang.NullPointerException
            at rtdc.android.presenter.fragments.CommunicationHubFragment.onUsersFetched(CommunicationHubFragment.java:98)
            at rtdc.core.event.FetchUsersEvent.fire(FetchUsersEvent.java:41)
            at rtdc.core.event.Event.fire(Event.java:38)
            at rtdc.core.service.Service$1.onSuccess(Service.java:101)
            at rtdc.core.service.Service$1.onSuccess(Service.java:93)
            at rtdc.android.impl.AndroidHttpRequest$1.onResponse(AndroidHttpRequest.java:62)
            at rtdc.android.impl.AndroidHttpRequest$1.onResponse(AndroidHttpRequest.java:58)
            at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:60)
            at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:30)
            at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
            at android.os.Handler.handleCallback(Handler.java:725)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5041)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Fadorico** [comment]
It's most likely because we never unsubscribe for user fetched events.
