### ISSUE TITLE
Add User Crash

### ISSUE THREAD

**Issue by Nicolas-M** [Bathlamos/RTDC#69]
After trying to add a user, all seems to work for a few seconds until the application crashes. When I dismiss the crash, I am brought back to the new user dialog with all the information that I had previously filled. Here is the stacktrace:
```
android.view.WindowManager$BadTokenException: Unable to add window -- token null is not for an application
            at android.view.ViewRootImpl.setView(ViewRootImpl.java:571)
            at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:246)
            at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
            at android.app.Dialog.show(Dialog.java:281)
            at android.app.AlertDialog$Builder.show(AlertDialog.java:951)
            at rtdc.android.presenter.fragments.AbstractFragment.displayError(AbstractFragment.java:25)
            at rtdc.core.controller.Controller.onError(Controller.java:19)
            at rtdc.core.event.ErrorEvent.fire(ErrorEvent.java:34)
            at rtdc.core.service.Service$1.onError(Service.java:110)
            at rtdc.android.impl.AndroidHttpRequest$2.onErrorResponse(AndroidHttpRequest.java:69)
            at com.android.volley.Request.deliverError(Request.java:592)
            at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:101)
            at android.os.Handler.handleCallback(Handler.java:725)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5041)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)
```
Saving the user for a second time causes more errors, as seen by the following two stack traces:

```
java.lang.NullPointerException
            at rtdc.core.service.Service.updateOrSaveUser(Service.java:66)
            at rtdc.core.controller.AddUserController.addUser(AddUserController.java:53)
            at rtdc.android.presenter.CreateUserActivity.onOptionsItemSelected(CreateUserActivity.java:95)
            at android.app.Activity.onMenuItemSelected(Activity.java:2548)
            at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:350)
            at android.support.v7.app.ActionBarActivity.onMenuItemSelected(ActionBarActivity.java:155)
            at android.support.v7.app.ActionBarActivityDelegate$1.onMenuItemSelected(ActionBarActivityDelegate.java:74)
            at android.support.v7.widget.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:44)
            at android.support.v7.internal.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:77)
            at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:162)
            at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:738)
            at android.support.v7.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:802)
            at android.support.v7.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
            at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:949)
            at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:939)
            at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:596)
            at android.support.v7.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:145)
            at android.view.View.performClick(View.java:4204)
            at android.view.View$PerformClick.run(View.java:17355)
            at android.os.Handler.handleCallback(Handler.java:725)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5041)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)
```

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{rtdc.android/rtdc.android.presenter.MainActivity}: java.lang.NullPointerException
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2180)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
            at android.app.ActivityThread.access$600(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5041)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
            at rtdc.core.service.Service.getUsers(Service.java:62)
            at rtdc.core.controller.UserListController.<init>(UserListController.java:22)
            at rtdc.android.presenter.fragments.ManageUsersFragment.onCreateView(ManageUsersFragment.java:46)
            at android.app.Fragment.performCreateView(Fragment.java:1699)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:885)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1057)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1039)
            at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1840)
            at android.app.Activity.performCreate(Activity.java:5107)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
            at android.app.ActivityThread.access$600(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5041)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)
```

Last note: I can't reproduce this bug everytime. It has happened more then once to me however.

**Comment by Nicolas-M** [comment]
I think this error might be link to the fact that the auth token expires (for some reason) and then the server returns a 401 (Not authorized). After talking with @Bathlamos, we decided to redirect users to the login activity when that happens. Implemented in 189a1ca6eb5c0ffde73982910db8ba7df93755a8
