### ISSUE TITLE
Exiting app with Back button makes app crash when reopening

### ISSUE THREAD

**Issue by Shern** [Bathlamos/RTDC#84]

**Comment by Nicolas-M** [comment]
I tried logging in, but as soon as I did, the application crashed because of the AndroidVoipController. I think our errors are related, so I'm posting here. Below is the (long) stacktrace I got:

````
09-21 03:43:18.212    1759-1759/rtdc.android I/LinphoneCoreFactoryImpl﹕ Trying to load liblinphone for x86
09-21 03:43:18.212    1759-1759/rtdc.android W/LinphoneCoreFactoryImpl﹕ Unable to load optional library libffmpeg-linphone-x86
09-21 03:43:18.212    1759-1759/rtdc.android D/dalvikvm﹕ Trying to load lib /data/app-lib/rtdc.android-1/liblinphone-x86.so 0xb2ee8670
09-21 03:43:18.212    1759-1759/rtdc.android E/dalvikvm﹕ dlopen("/data/app-lib/rtdc.android-1/liblinphone-x86.so") failed: Cannot load library: soinfo_link_image(linker.cpp:1635): could not load library "libffmpeg-linphone-x86.so" needed by "liblinphone-x86.so"; caused by load_library(linker.cpp:745): library "libffmpeg-linphone-x86.so" not found
09-21 03:43:18.212    1759-1759/rtdc.android I/LinphoneCoreFactoryImpl﹕ Trying to load liblinphone for unknown
09-21 03:43:18.212    1759-1759/rtdc.android W/LinphoneCoreFactoryImpl﹕ Unable to load optional library libffmpeg-linphone-unknown
09-21 03:43:18.212    1759-1759/rtdc.android W/dalvikvm﹕ Exception Ljava/lang/RuntimeException; thrown while initializing Lorg/linphone/core/LinphoneCoreFactoryImpl;
09-21 03:43:18.212    1759-1759/rtdc.android W/dalvikvm﹕ Exception Ljava/lang/ExceptionInInitializerError; thrown while initializing Lrtdc/android/voip/LiblinphoneThread;
09-21 03:43:18.212    1759-1759/rtdc.android D/AndroidRuntime﹕ Shutting down VM
09-21 03:43:18.212    1759-1759/rtdc.android W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0xb2c92908)
09-21 03:43:18.212    1759-1759/rtdc.android E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.ExceptionInInitializerError
            at rtdc.android.impl.AndroidVoipController.registerUser(AndroidVoipController.java:32)
            at rtdc.core.controller.LoginController.onAuthenticate(LoginController.java:53)
            at rtdc.core.event.AuthenticationEvent.fire(AuthenticationEvent.java:41)
            at rtdc.core.event.Event.fire(Event.java:38)
            at rtdc.core.service.Service$1.onSuccess(Service.java:97)
            at rtdc.core.service.Service$1.onSuccess(Service.java:89)
            at rtdc.android.impl.AndroidHttpRequest$1.onResponse(AndroidHttpRequest.java:62)
            at rtdc.android.impl.AndroidHttpRequest$1.onResponse(AndroidHttpRequest.java:58)
            at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:67)
            at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:30)
            at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
            at android.os.Handler.handleCallback(Handler.java:725)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5041)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ExceptionInInitializerError
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:217)
            at java.lang.Class.forName(Class.java:172)
            at org.linphone.core.LinphoneCoreFactory.instance(LinphoneCoreFactory.java:44)
            at rtdc.android.voip.LiblinphoneThread.<init>(LiblinphoneThread.java:26)
            at rtdc.android.voip.LiblinphoneThread.<clinit>(LiblinphoneThread.java:22)
            at rtdc.android.impl.AndroidVoipController.registerUser(AndroidVoipController.java:32)
            at rtdc.core.controller.LoginController.onAuthenticate(LoginController.java:53)
            at rtdc.core.event.AuthenticationEvent.fire(AuthenticationEvent.java:41)
            at rtdc.core.event.Event.fire(Event.java:38)
            at rtdc.core.service.Service$1.onSuccess(Service.java:97)
            at rtdc.core.service.Service$1.onSuccess(Service.java:89)
            at rtdc.android.impl.AndroidHttpRequest$1.onResponse(AndroidHttpRequest.java:62)
            at rtdc.android.impl.AndroidHttpRequest$1.onResponse(AndroidHttpRequest.java:58)
            at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:67)
            at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:30)
            at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
            at android.os.Handler.handleCallback(Handler.java:725)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5041)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: Cannot load library: soinfo_link_image(linker.cpp:1635): could not load library "libffmpeg-linphone-x86.so" needed by "liblinphone-x86.so"; caused by load_library(linker.cpp:745): library "libffmpeg-linphone-x86.so" not found
            at org.linphone.core.LinphoneCoreFactoryImpl.<clinit>(LinphoneCoreFactoryImpl.java:67)
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:217)
            at java.lang.Class.forName(Class.java:172)
            at org.linphone.core.LinphoneCoreFactory.instance(LinphoneCoreFactory.java:44)
            at rtdc.android.voip.LiblinphoneThread.<init>(LiblinphoneThread.java:26)
            at rtdc.android.voip.LiblinphoneThread.<clinit>(LiblinphoneThread.java:22)
            at rtdc.android.impl.AndroidVoipController.registerUser(AndroidVoipController.java:32)
            at rtdc.core.controller.LoginController.onAuthenticate(LoginController.java:53)
            at rtdc.core.event.AuthenticationEvent.fire(AuthenticationEvent.java:41)
            at rtdc.core.event.Event.fire(Event.java:38)
            at rtdc.core.service.Service$1.onSuccess(Service.java:97)
            at rtdc.core.service.Service$1.onSuccess(Service.java:89)
            at rtdc.android.impl.AndroidHttpRequest$1.onResponse(AndroidHttpRequest.java:62)
            at rtdc.android.impl.AndroidHttpRequest$1.onResponse(AndroidHttpRequest.java:58)
            at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:67)
            at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:30)
            at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
            at android.os.Handler.handleCallback(Handler.java:725)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5041)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: soinfo_link_image(linker.cpp:1635): could not load library "libffmpeg-linphone-x86.so" needed by "liblinphone-x86.so"; caused by load_library(linker.cpp:745): library "libffmpeg-linphone-x86.so" not found
            at java.lang.Runtime.loadLibrary(Runtime.java:371)
            at java.lang.System.loadLibrary(System.java:535)
            at org.linphone.core.LinphoneCoreFactoryImpl.<clinit>(LinphoneCoreFactoryImpl.java:57)
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:217)
            at java.lang.Class.forName(Class.java:172)
            at org.linphone.core.LinphoneCoreFactory.instance(LinphoneCoreFactory.java:44)
            at rtdc.android.voip.LiblinphoneThread.<init>(LiblinphoneThread.java:26)
            at rtdc.android.voip.LiblinphoneThread.<clinit>(LiblinphoneThread.java:22)
            at rtdc.android.impl.AndroidVoipController.registerUser(AndroidVoipController.java:32)
            at rtdc.core.controller.LoginController.onAuthenticate(LoginController.java:53)
            at rtdc.core.event.AuthenticationEvent.fire(AuthenticationEvent.java:41)
            at rtdc.core.event.Event.fire(Event.java:38)
            at rtdc.core.service.Service$1.onSuccess(Service.java:97)
            at rtdc.core.service.Service$1.onSuccess(Service.java:89)
            at rtdc.android.impl.AndroidHttpRequest$1.onResponse(AndroidHttpRequest.java:62)
            at rtdc.android.impl.AndroidHttpRequest$1.onResponse(AndroidHttpRequest.java:58)
            at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:67)
            at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:30)
            at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
            at android.os.Handler.handleCallback(Handler.java:725)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5041)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)
````

**Comment by Nicolas-M** [comment]
The missing .so files were probably at the root of the issue. Closing issue.
